stages:
  - build
  - release

build_job:
  image: python:3.12-slim
  stage: build
  only:
    - main
  services:
    - name: postgres:16.3
      alias: postgres
  variables:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"
    POSTGRES_DB: "fastapi_boilerplate"
    PIP_ONLY_BINARY: ":all:"
    PDM_ONLY_BINARY: ":all:"
    PDM_CHECK_UPDATE: "false"
    APP_NAME: "fastapi-boilerplate"
    APP_HOST: "127.0.0.1"
    APP_PORT: "4000"
    DATABASE_URL: "postgresql://postgres:password@postgres:5432/fastapi_boilerplate?schema=public"
  script:
    - pip install --index-url ${PIP_INDEX_URL} pdm
    - python -m venv .venv
    - pdm install
    - pdm run migrate-deploy
    - pdm run lint
    - pdm run test-cov
    - pdm run license-check

release_job:
  image: docker:24
  stage: release
  only:
    - main
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    VERSION: "main"
  before_script:
    - docker info
  script:
    - docker login -u $COOKDING_REGISTRY_USERNAME -p $COOKDING_REGISTRY_PASSWORD $COOKDING_REGISTRY
    - docker pull $COOKDING_REGISTRY/cookding/fastapi-boilerplate:latest || true
    - |
      docker build --cache-from $COOKDING_REGISTRY/cookding/fastapi-boilerplate:latest \
      --build-arg APT_DEBIAN_MIRROR_HOST=${APT_DEBIAN_MIRROR_HOST} \
      --build-arg PIP_INDEX_URL=${PIP_INDEX_URL} \
      --build-arg PDM_PYPI_URL=${PDM_PYPI_URL} \
      --build-arg PDM_PYPI_USERNAME=${PDM_PYPI_USERNAME} \
      --build-arg PDM_PYPI_PASSWORD=${PDM_PYPI_PASSWORD} \
      --tag $COOKDING_REGISTRY/cookding/fastapi-boilerplate:$VERSION .
    - docker push $COOKDING_REGISTRY/cookding/fastapi-boilerplate:$VERSION
    - docker tag $COOKDING_REGISTRY/cookding/fastapi-boilerplate:$VERSION $COOKDING_REGISTRY/cookding/fastapi-boilerplate:latest
    - docker push $COOKDING_REGISTRY/cookding/fastapi-boilerplate:latest
