stages:
  - build
  - release

build_job:
  image: python:3.11-slim
  stage: build
  only:
    - main
  services:
    - name: postgres:16.3
      alias: postgres
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: fastapi_boilerplate
    PDM_CHECK_UPDATE: false
    APP_NAME: fastapi-boilerplate
    APP_HOST: 127.0.0.1
    APP_PORT: 4000
    DATABASE_URL: postgresql://postgres:password@postgres:5432/fastapi_boilerplate?schema=public
  script:
    - |
      set -eux; \
      sed -i "s/deb.debian.org/${APT_DEBIAN_MIRROR_HOST}/g" /etc/apt/sources.list.d/debian.sources; \
      apt-get update; \
      apt-get install -y --no-install-recommends \
        nodejs \
        npm \
        openssl \
      ;
    - pip install --index-url ${PIP_INDEX_URL} pdm
    - python -m venv .venv
    - pdm install
    - npm config set registry "${NPM_REGISTRY}"
    - npm config set "${NPM_REGISTRY_TOKEN_KEY}" "${NPM_REGISTRY_TOKEN_VALUE}"
    - pdm run prisma-generate
    - pdm run migrate-deploy
    - pdm run lint
    - pdm run test-cov

release_job:
  image: docker:24
  stage: release
  only:
    - main
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    VERSION: "main"
  before_script:
    - docker info
  script:
    - docker login -u $CI_DOCKER_REGISTRY_USERNAME -p $CI_DOCKER_REGISTRY_PASSWORD $CI_DOCKER_REGISTRY
    - docker pull $CI_DOCKER_REGISTRY/cookding/foundation/fastapi-boilerplate:latest || true
    - |
      docker build --cache-from $CI_DOCKER_REGISTRY/cookding/foundation/fastapi-boilerplate:latest \
      --build-arg APT_DEBIAN_MIRROR_HOST=${APT_DEBIAN_MIRROR_HOST} \
      --build-arg PIP_INDEX_URL=${PIP_INDEX_URL} \
      --build-arg PDM_PYPI_URL=${PDM_PYPI_URL} \
      --build-arg PDM_PYPI_USERNAME=${PDM_PYPI_USERNAME} \
      --build-arg PDM_PYPI_PASSWORD=${PDM_PYPI_PASSWORD} \
      --build-arg NPM_REGISTRY=${NPM_REGISTRY} \
      --build-arg NPM_REGISTRY_TOKEN_KEY=${NPM_REGISTRY_TOKEN_KEY} \
      --build-arg NPM_REGISTRY_TOKEN_VALUE=${NPM_REGISTRY_TOKEN_VALUE} \
      --tag $CI_DOCKER_REGISTRY/cookding/foundation/fastapi-boilerplate:$VERSION .
    - docker push $CI_DOCKER_REGISTRY/cookding/foundation/fastapi-boilerplate:$VERSION
    - docker tag $CI_DOCKER_REGISTRY/cookding/foundation/fastapi-boilerplate:$VERSION $CI_DOCKER_REGISTRY/cookding/foundation/fastapi-boilerplate:latest
    - docker push $CI_DOCKER_REGISTRY/cookding/foundation/fastapi-boilerplate:latest
